---
dependencies: []

galaxy_info:
  role_name: ndm_wireguard
  author: "Ivan Andreev"
  description: "setup wireguard on keenetic ndms"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: NXOS
      versions:
        - any

  galaxy_tags:
    - keenetic
    - ndms
    - wireguard
    - vpn

  github_branch: master
...
