---
- name: query ndm interface states
  restconf_get:
    path: /show/interface
  register: ndm_if_states
  until: ndm_if_states is successful

- name: query ndm interface configs
  restconf_get:
    path: /show/rc/interface
  register: ndm_if_configs
  until: ndm_if_configs is successful

- name: find outdated wireguard interfaces
  debug:
    msg: "{{ item.name }} {{ outdated |bool |ternary('needs update', 'is ok') }}"
  changed_when: outdated
  loop: "{{ ndm_wg_peers |d([],true) }}"
  loop_control:
    index_var: idx
    label: "{{ item.name }}"
  register: ndm_wg_check
  vars:
    ifname: "Wireguard{{ idx }}"
    cfg: "{{ ndm_if_configs.response[ifname] |d({}) }}"
    state: "{{ ndm_if_states.response[ifname] |d({}) }}"
    old_config: "{{ lookup('template', 'old_config.json.j2') |to_json }}"
    new_config: "{{ lookup('template', 'new_config.json.j2') |to_json }}"
    old_pubkey: "{{ state.wireguard['public-key'] |d('?') }}"
    new_pubkey: "{{ ndm_wg_pub }}"
    priv_key: 'cannot check private key'
    outdated: "{{ old_config != new_config or old_pubkey != new_pubkey }}"

- name: flush outdated wireguard interfaces
  restconf_config2:
    path: "/interface/Wireguard{{ idx }}"
    content: '{"no": true}'
  when: ndm_wg_check.results[idx].changed
  loop: "{{ ndm_wg_peers |d([],true) }}"
  loop_control:
    label: "{{ item.name }}"
    index_var: idx
  tags: skip_ansible_lint

- name: configure wireguard interfaces
  restconf_config2:
    path: "/interface/Wireguard{{ idx }}"
    content: "{{ lookup('template', 'new_config.json.j2') |to_json }}"
  loop: "{{ ndm_wg_peers |d([],true) }}"
  loop_control:
    label: "{{ item.name }}"
    index_var: idx
  vars:
    priv_key: "{{ ndm_wg_key }}"
  when: ndm_wg_check.results[idx].changed
  tags: skip_ansible_lint

- name: save new wireguard configuration
  restconf_config2:
    path: /system/configuration
    content: '{"save": true}'
  ## flush_handlers is unsupported on this connection
  when: ndm_wg_check is changed
  tags: skip_ansible_lint
...
